# Generated by Django 2.2.6 on 2019-10-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('image_url', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('price', models.CharField(blank=True, default=None, max_length=65, null=True)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
